[build]
  command = "hugo --minify --gc --cleanDestinationDir"

[build.environment]
  HUGO_VERSION = "0.100.1"

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/webfonts/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*"

[headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "'default-src' 'self' data: 'unsafe-eval' 'unsafe-inline' www.google-analytics.com www.googletagmanager.com https://i.imgur.com https://res.cloudinary.com www.youtube-nocookie.com www.youtube.com "